yt-dlp:
  # yt-dlp程序路径
  program-location: 'C:\Users\YangHgRi\AppData\Local\Programs\Python\Python310\Scripts\yt-dlp.exe'
  # 配置文件路径
  config-location: 'D:\MediaLib\yt-dlp.conf'
  # 关键字集合，与url-list和work-dir有强耦合关系，在这个list中的元素和其索引就对应ulr-list、work-dir这两个map的key和客户端输入的序号（ordinal）
  key-list:
    - 'youtube'
    - 'bilibili'
    - 'pornhub'
    - 'game'
    - 'asmr'
    - 'asmr_audio'
  # 批量下载url列表路径
  url-list:
    -youtube: 'D:\MediaLib\url-list\youtube-list.txt'
    -bilibili: 'D:\MediaLib\url-list\bilibili-list.txt'
    -pornhub: 'D:\MediaLib\url-list\pornhub-list.txt'
    -game: 'D:\MediaLib\url-list\game-list.txt'
    -asmr: 'D:\MediaLib\url-list\asmr-list.txt'
    -asmr_audio: 'D:\MediaLib\url-list\asmr-audio-list.txt'
  # yt-dlp工作目录
  work-dir:
    -youtube: 'D:\MediaLib\数一数二\油管'
    -bilibili: 'D:\MediaLib\数一数二\阿B'
    -pornhub: 'D:\MediaLib\Pornhub'
    -game: 'D:\MediaLib\游戏视频'
    -asmr: 'D:\ASMR'
    -asmr_audio: 'D:\ASMR'